version: "3.8"

services:

  backend:
    build: .
    container_name: ml-predict-api
    ports:
      - "8443:8443"
    expose:
      - "8443"

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - backend
